// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyxADxwULhie3_7PGLfnw98f7oXBlXXNU',
    appId: '1:595475256228:web:7f7483b7f8033164992731',
    messagingSenderId: '595475256228',
    projectId: 'nectar-11',
    authDomain: 'nectar-11.firebaseapp.com',
    storageBucket: 'nectar-11.firebasestorage.app',
    measurementId: 'G-9D5C0ECFP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB89y0Nb7zbae1nsGuGq8FeLUqvZQ-trLg',
    appId: '1:595475256228:android:57355b71dae9a0ae992731',
    messagingSenderId: '595475256228',
    projectId: 'nectar-11',
    storageBucket: 'nectar-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3_2kXTz6YuEEe5ZJ1p6GtLVuQSakI__o',
    appId: '1:595475256228:ios:e188a9e8faf2886a992731',
    messagingSenderId: '595475256228',
    projectId: 'nectar-11',
    storageBucket: 'nectar-11.firebasestorage.app',
    iosClientId: '595475256228-rimenb601gv4m2aepn483504vnr4re0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceriesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3_2kXTz6YuEEe5ZJ1p6GtLVuQSakI__o',
    appId: '1:595475256228:ios:e188a9e8faf2886a992731',
    messagingSenderId: '595475256228',
    projectId: 'nectar-11',
    storageBucket: 'nectar-11.firebasestorage.app',
    iosClientId: '595475256228-rimenb601gv4m2aepn483504vnr4re0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceriesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyxADxwULhie3_7PGLfnw98f7oXBlXXNU',
    appId: '1:595475256228:web:c70e2403550a1377992731',
    messagingSenderId: '595475256228',
    projectId: 'nectar-11',
    authDomain: 'nectar-11.firebaseapp.com',
    storageBucket: 'nectar-11.firebasestorage.app',
    measurementId: 'G-3MK5X7JYPZ',
  );
}
